from .anaconda import Anaconda
from .beta import Beta
from .copperhead import Copperhead
from .donkey import Donkey
from .goat import Goat
from .goldfish import Goldfish
from .koi import Koi
from .llama import Llama
from .mallard import Mallard
from .python import Python
from .rabbit import Rabbit
from .rat_snake import Rat_Snake
from .salmon import Salmon
from .sheep import Sheep
from .viper import Viper
from .goose import Goose